services:
  database:
    image: mariadb:11.3
    container_name: time_tracking_mariadb
    command: --default-auth=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: time_tracking_system
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
    ports:
      - "3333:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - time_tracking_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: time_tracking_phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 300M
    ports:
      - "8888:80"
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - time_tracking_network

volumes:
  mariadb_data:

networks:
  time_tracking_network:
    driver: bridge