# config/services.yaml
parameters:
    monthly_norm: '%env(int:MONTHLY_NORM)%'
    base_rate: '%env(int:BASE_RATE)%'
    overtime_multiplier: '%env(float:OVERTIME_MULTIPLIER)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $monthlyNorm: '%monthly_norm%'
            $baseRate: '%base_rate%'
            $overtimeMultiplier: '%overtime_multiplier%'

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Infra\HoursProcessor: ~
    App\Repository\WorkTimeRepository: ~
    
    App\Domain\Service\PayrollCalculator: ~
    
    App\Service\Strategy\MonthlySummaryStrategy:
        arguments:
            $payrollCalculator: '@App\Domain\Service\PayrollCalculator'
    
    App\Service\Strategy\DailySummaryStrategy:
        arguments:
            $payrollCalculator: '@App\Domain\Service\PayrollCalculator'
    App\Domain\Rule\SummaryRequestValidator: ~
    App\Domain\Rule\EmployeeValidator: ~
    App\Service\WorkTimeService: ~
    App\Domain\Validator\WorkTimeValidator: ~
    App\Domain\Validator\UniqueDayValidator: ~
    App\Domain\Validator\MaxHoursValidator: ~

    App\EventListener\ExceptionListener:
        arguments:
            $debug: '%kernel.debug%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Service\SummaryService:
        arguments:
            $workTimeRepository: '@App\Repository\WorkTimeRepository'
            $hoursProcessor: '@App\Infra\HoursProcessor'
            $monthlyStrategy: '@App\Service\Strategy\MonthlySummaryStrategy'
            $dailyStrategy: '@App\Service\Strategy\DailySummaryStrategy'
            $validator: '@App\Domain\Rule\SummaryRequestValidator'
            $employeeChecker: '@App\Domain\Rule\EmployeeValidator'
            $dateRangeResolver: '@App\Domain\Rule\DateRangeResolver'